@baseUrl = http://localhost:3000
@JwtToken = {{authLogin.response.body.accessToken}}

### Auth Login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "123456"
}


### Read One User
# @name readOneUser
GET {{baseUrl}}/user/12
Authorization: Bearer {{JwtToken}}

### Read One User
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Erickson Costa",
  "email": "user@example.com",
  "password": "123456"
}

### Update User
# @name updateUser

PATCH  {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{JwtToken}}

{
  "name": "Erickson Costa",
  "email": "user@example.com"
}

### Update User Password
# @name updateUserPassword
PATCH  {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{JwtToken}}

{
  "currentPassword": "123456",
  "newPassword": "654321"
}

### Read One User
# @name readOneUser
GET  {{baseUrl}}/user/me
Authorization: Bearer {{JwtToken}}

### Delete One User
# @name deleteOneUser
DELETE   {{baseUrl}}/user/me
Authorization: Bearer {{JwtToken}}

